### ISSUE TITLE
Enable precompilation

### ISSUE THREAD

**Issue by SebastianM-C** [libAtoms/ASE.jl#17]
Since the python dependencies are installed via Conda and MolSimPy is behind Requires, I think it would be safe to enable precompilation.
I can make a PR if you agree.

**Comment by cortner** [comment]
Sounds great I’m principle. Please give me a chance to review the code base though. I haven’t looked at ASE.jl in a while

**Comment by cortner** [comment]
Ok I agree. I’ll be grateful for a PR, since I don’t have much time right now.

In general if you want to contribute to our ecosystem in any way I’ll be very grateful!
