### ISSUE TITLE
Should the `read_xyz` function be named as it is?

### ISSUE THREAD

**Issue by rashidrafeek** [libAtoms/ASE.jl#19]
The `read_xyz` in this  wraps the `ase.io.read` function. But the latter can read a large number of formats and is not restricted to xyz files. So shouldn't the function be named something like `readatoms`?

**Comment by cortner** [comment]
Thanks for the suggestion. I've never used other formats hence never thought about it but it makes perfect sense. Would you be interested in making a PR? But could you please keep the `read_xyz` function for compatibility? But it could maybe just call `readatoms`.

**Comment by rashidrafeek** [comment]
Sure, I will try and make a PR.
