### ISSUE TITLE
reading Cu data with pymatgen

### ISSUE THREAD

**Issue by andresrossb** [libAtoms/ASE.jl#22]
```Julia
using PyCall
ase = pyimport("ase")
pmt = pyimport("pymatgen.core")
pmt2ase = pyimport("pymatgen.io.ase")
json = pyimport("json")

f = open("data/training.json", "r")
data = json.load(f)
Xase = []
for d in data
   curr_structure = pmt.Structure.from_dict(d["structure"])
   at = pmt2ase.AseAtomsAdaptor.get_atoms(curr_structure)
   append!(Xase, at)
end

using ASE, JuLIP
X = []
for x in Xase
   curr_at = Atoms(ASEAtoms(x))
   append!(X, curr_at)
end
```

python = v"3.9.5"
PyCall = v1.93.0

**Comment by cortner** [comment]
what is are the versions of `ase` and what is the error?

**Comment by cortner** [comment]
ok I think I can reproduce: 
```Julia
Xase[1].get_positions()
# ERROR: LoadError: KeyError: key :get_positions not found
```

**Comment by cortner** [comment]
this is not a bug in ASE but a subtle bug in your script: `append!(Xase, at)` should be `push!`

**Comment by andresrossb** [comment]
ASE v0.5.4

ERROR: LoadError: KeyError: key :get_positions not found
Stacktrace:
 [1] __getproperty(o::PyObject, s::Symbol)
   @ PyCall C:\Users\andre\.julia\packages\PyCall\L0fLP\src\PyCall.jl:307
 [2] getproperty
   @ C:\Users\andre\.julia\packages\PyCall\L0fLP\src\PyCall.jl:312 [inlined]
 [3] positions(at::ASEAtoms)
   @ ASE C:\Users\andre\.julia\packages\ASE\0hdBq\src\ASE.jl:99
 [4] Atoms(at_ase::ASEAtoms)
   @ ASE C:\Users\andre\.julia\packages\ASE\0hdBq\src\ASE.jl:164
 [5] top-level scope
   @ g:\My Drive\documents\UBC\Julia Codes\testNL\copperPyRead.jl:22
in expression starting at g:\My Drive\documents\UBC\Julia Codes\testNL\copperPyRead.jl:21

**Comment by cortner** [comment]
same with the second loop.

**Comment by cortner** [comment]
here is the correct script; this seems to read in the data ok for me. 
```Julia
using PyCall
ase = pyimport("ase")
pmt = pyimport("pymatgen.core")
pmt2ase = pyimport("pymatgen.io.ase")
json = pyimport("json")

f = open(@__DIR__() * "/training.json", "r")
data = json.load(f)
Xase = []
for d in data
   curr_structure = pmt.Structure.from_dict(d["structure"])
   at = pmt2ase.AseAtomsAdaptor.get_atoms(curr_structure)
   push!(Xase, at)
end

using ASE, JuLIP
X = []
for x in Xase
   curr_at = Atoms(ASEAtoms(x))
   push!(X, curr_at)
end
```

**Comment by andresrossb** [comment]
Yes, this works for me too. I'm sorry I got confused with my python and my Julia.

**Comment by cortner** [comment]
no worries - and yes, it seems we imported incorrectly.
