### ISSUE TITLE
Updated Reexport.jl version

### ISSUE THREAD

**Issue by stefanbringuier** [libAtoms/ASE.jl#24]
I'm trying to utilize ASE.jl in my project, but I have a `ERROR: unsatisfiable requirements detected for package Reexport[189a3867]`, specifically it's an issue with the [JLD2.jl](https://github.com/JuliaIO/JLD2.jl) package which requires `Reexport.jl`  and  another package using `JLD2.jl` wanting version `1.0.0-1.2.2` due to compatibility constraint. I forked ASE.jl to just take care of this for my needs, but then I noticed there is a compatibility constraint with [JuLIP.jl](https://github.com/JuliaMolSim/JuLIP.jl). Any chance ASE.jl and JuLIP.jl dependency on [Reexport.jl](https://github.com/simonster/Reexport.jl) get pulled up to 1.0.0 or greater?

**Comment by cortner** [comment]
You may want ACE1.jl - can you please tell me quickly what you are planning to use it for? If you are after interatomic potential e.g. then please look at [ACE1pack.jl](https://github.com/ACEsuit/ACE1pack.jl)

**Comment by cortner** [comment]
note also that I'm currently in the process of registering everything with General, but it is currently in the MolSim registry. So that's another potential source of confusions.

**Comment by stefanbringuier** [comment]
@cortner my use is for high-throughput processing of DFT calculations with code/scripts I'm developing, and I was hoping to use ASE.jl rather than setting up ASE in Conda.jl /PyCall.jl directly.

Thanks for pointing me to ACE1.jl, I'll have to check this out for potential development activities I have.

**Comment by cortner** [comment]
got it - sorry, I was getting very confused. Can you please try and see if the following fixes it for you: 
```
] registry add https://github.com/JuliaMolSim/MolSim.git
add ASE, JuLIP 
up
```
This should get the latest versions of ASE.jl and JuLIP.jl up and running. As I said, I'm trying to get them registered back in General, but I'm stuck with [this PR](https://github.com/JuliaRegistries/General/pull/69894)

**Comment by stefanbringuier** [comment]
Yep, that did works for me, thank you! Hopefully, you're able to get the packages in the General Julia registry.
