### ISSUE TITLE
Length limit on extxyz info dict representation

### ISSUE THREAD

**Issue by MorrowChem** [libAtoms/ASE.jl#25]
## Issue with `read_extxyz` and Long Lines in Structures

The `read_extxyz` function encounters an error with the message "Failed to parse string at pos 101" when attempting to read a structure containing a long line. While the following example may seem contrived, even a modest amount of array data within the info dictionary can quickly surpass the limit. This issue was first identified on a real database.

**Example File:** [minimal.xyz.txt](https://github.com/JuliaMolSim/ASE.jl/files/12431196/minimal.xyz.txt)

**Comment by cortner** [comment]
This seems unrelated to `ASE.jl` - if you agree, can you close and file the issue with [`ExtXYZ.jl`](https://github.com/libAtoms/ExtXYZ.jl)?

**Comment by MorrowChem** [comment]
agreed
