### ISSUE TITLE
ASE segfaults

### ISSUE THREAD

**Issue by cortner** [libAtoms/ASE.jl#4]
I can't use `ASE.jl` anymore - it segfaults almost immediately. Though funnily it seems I can access `ase` directly via `PyCall`.

@gabor1 @jameskermode @dussong when you have 5 minutes would you be willing to run the following test for me:
```
Pkg.status("ASE")
Pkg.status("PyCall")
using PyCall
@pyimport ase 
@show ase.__version__
```
then open a fresh REPL and run 
```
using ASE 
bulk("Si")
```

Thank you.

**Comment by jameskermode** [comment]
ok for me with Julia 0.6.2 in the libatomsquip Docker image:

```
julia> Pkg.status("ASE")
 - ASE                           0.1.0

julia> Pkg.status("PyCall")
 - PyCall                        1.15.0

julia> using PyCall

julia> @pyimport ase

julia> @show ase.__version__
ase.__version__ = "3.16.0"
"3.16.0"
```

new  REPL:

```
julia> using ASE

julia> bulk("Si")
ASE.ASEAtoms(PyObject Atoms(symbols='Si2', pbc=True, cell=[[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]]), JuLIP.NullCalculator(), JuLIP.NullConstraint(), Dict{Any,ASE.TransientData}())
```

**Comment by jameskermode** [comment]
(trying on my Mac directly, but it needs to update lots of Julia packages)

**Comment by dussong** [comment]
I am using Julia 0.6.4.

```
julia> Pkg.status("ASE")
 - ASE                           0.1.0+             master

julia> Pkg.status("PyCall")
 - PyCall                        1.17.1+            master

julia> using PyCall

julia> @pyimport ase

julia> @show ase.__version__
ase.__version__ = "3.15.0"
"3.15.0"

```
Then
```
julia> using ASE

julia> bulk("Si")

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
```

**Comment by jameskermode** [comment]
Given up, my local Julia installation is too broken

**Comment by gabor1** [comment]
Worked for me in the docker (which I upgraded to us Julia 0.6.4). my ase.__version__ is one later than the one that failed for you!



julia> using ASE
INFO: Recompiling stale cache file /opt/julia/share/site/lib/v0.6/JuLIP.ji for module JuLIP.

julia> bulk("Si")
ASE.ASEAtoms(PyObject Atoms(symbols='Si2', pbc=True, cell=[[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]]), JuLIP.NullCalculator(), JuLIP.NullConstraint(), Dict{Any,ASE.TransientData}())

julia> Pkg.status("ASE")
 - ASE                           0.1.0

julia> Pkg.status("PyCall")
 - PyCall                        1.17.1

julia> @show ase.version
ERROR: UndefVarError: ase not defined

julia> using PyCall

julia> @pyimport ase

julia> @show ase.version
ERROR: UndefVarError: version not defined

julia> @show ase.__version__
ase.__version__ = "3.16.0"
"3.16.0"

julia> 




> On 3 Sep 2018, at 09:54, James Kermode <notifications@github.com> wrote:
> 
> Given up, my local Julia installation is too broken
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by cortner** [comment]
thank you all - I'll assume this is a pure Mac problem then and will start debugging :(

**Comment by jameskermode** [comment]
If you can get a stack trace (e.g. via `gdb julia; run; bt`) I might be able to help work out what's going on

**Comment by cortner** [comment]
it seems this is a problem related to precompilation.  - turning it off seems to have resolved it.
