### ISSUE TITLE
Does not support Julia 1.0.0?

### ISSUE THREAD

**Issue by lixinyuu** [libAtoms/ASE.jl#6]
Hi, is ASE.jl does not support Julia 1.0.0?

I run
```
Pkg.add("ASE")
```
It returned with error:
```
Resolving package versions...
Unsatisfiable requirements detected for package ASE [51974c44]:
 ASE [51974c44] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
Is this mean that ASE.jl only support Julia 0.1.0? Thanks. (System: Windows10)

**Comment by cortner** [comment]
There is an entire ecosystem around molecular simulation which I haven’t had time to upgrade to 1.0 yet. This will probably happen over the course of the next 3-4 months. You can use it with 0.6.4 though

**Comment by cortner** [comment]
just an update on this: two packages on which ASE.jl depends have now been updated to 1.0 and 1.1. ASE.jl is next.

**Comment by cortner** [comment]
I just registered a new version `v0.3.0` which is 0.7, 1.0, 1.1 compatible
